/**
 * Bilingual (FR/EN) Service Contract Template
 * Generates a basic service agreement pre-filled with business and client details.
 */

export interface ContractData {
  providerName: string;
  providerAddress: string;
  providerNEQ?: string;
  clientName: string;
  clientAddress: string;
  serviceDescription: string;
  totalAmount: number;
  currency?: string;
  startDate: string;
  endDate?: string;
  paymentTerms?: string;
}

export function renderContract(data: ContractData): string {
  const {
    providerName,
    providerAddress,
    providerNEQ,
    clientName,
    clientAddress,
    serviceDescription,
    totalAmount,
    currency = 'CAD',
    startDate,
    endDate,
    paymentTerms = 'Net 30',
  } = data;

  const formattedAmount = new Intl.NumberFormat('en-CA', {
    style: 'currency',
    currency,
  }).format(totalAmount);

  return `<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8" />
  <title>Contrat de services / Service Contract</title>
  <style>
    body { font-family: Arial, sans-serif; max-width: 800px; margin: 40px auto; color: #333; line-height: 1.6; }
    h1 { text-align: center; font-size: 20px; }
    .bilingual { display: grid; grid-template-columns: 1fr 1fr; gap: 32px; margin: 24px 0; }
    .section { border-top: 1px solid #ccc; padding-top: 12px; margin-top: 24px; }
    .parties { background: #f9f9f9; padding: 16px; border-radius: 4px; margin: 16px 0; }
    .signature { display: grid; grid-template-columns: 1fr 1fr; gap: 32px; margin-top: 64px; }
    .sig-line { border-top: 1px solid #333; padding-top: 8px; text-align: center; font-size: 12px; color: #666; }
  </style>
</head>
<body>
  <h1>CONTRAT DE SERVICES / SERVICE CONTRACT</h1>

  <div class="parties">
    <strong>Prestataire de services / Service Provider:</strong><br/>
    ${providerName}<br/>
    ${providerAddress}
    ${providerNEQ ? `<br/>NEQ: ${providerNEQ}` : ''}
    <br/><br/>
    <strong>Client:</strong><br/>
    ${clientName}<br/>
    ${clientAddress}
  </div>

  <div class="bilingual">
    <div>
      <div class="section">
        <strong>1. Services</strong>
        <p>${serviceDescription}</p>
      </div>
      <div class="section">
        <strong>2. Rémunération</strong>
        <p>Le Client s'engage à payer la somme de <strong>${formattedAmount}</strong> pour les services rendus.</p>
        <p>Conditions de paiement : ${paymentTerms}</p>
      </div>
      <div class="section">
        <strong>3. Durée</strong>
        <p>Ce contrat entre en vigueur le ${startDate}${endDate ? ` et prend fin le ${endDate}` : ''}.</p>
      </div>
      <div class="section">
        <strong>4. Droit applicable</strong>
        <p>Ce contrat est régi par les lois de la province de Québec et les lois fédérales du Canada.</p>
      </div>
    </div>

    <div>
      <div class="section">
        <strong>1. Services</strong>
        <p>${serviceDescription}</p>
      </div>
      <div class="section">
        <strong>2. Compensation</strong>
        <p>The Client agrees to pay <strong>${formattedAmount}</strong> for the services rendered.</p>
        <p>Payment terms: ${paymentTerms}</p>
      </div>
      <div class="section">
        <strong>3. Term</strong>
        <p>This contract is effective as of ${startDate}${endDate ? ` and ends on ${endDate}` : ''}.</p>
      </div>
      <div class="section">
        <strong>4. Governing Law</strong>
        <p>This contract is governed by the laws of the Province of Quebec and the federal laws of Canada.</p>
      </div>
    </div>
  </div>

  <div class="signature">
    <div>
      <div class="sig-line">
        Signature du Prestataire / Service Provider Signature<br/>
        ${providerName}
      </div>
    </div>
    <div>
      <div class="sig-line">
        Signature du Client / Client Signature<br/>
        ${clientName}
      </div>
    </div>
  </div>

  <p style="font-size:10px;color:#999;text-align:center;margin-top:32px;">
    Generated by BZNS — Micro-Business Launchpad. Not legal advice. Consult a lawyer for complex agreements.
  </p>
</body>
</html>`;
}
