#!/usr/bin/env python3
"""
generate_funding_summary.py

Reads all JSON files in data/funding/ and generates a consolidated
funding summary in both JSON and Markdown formats.

Outputs:
  - data/funding/_summary.json
  - data/funding/_summary.md  (optional, for documentation)
"""

import json
from pathlib import Path


FUNDING_DIR = Path(__file__).parent.parent / "data" / "funding"
OUTPUT_JSON = FUNDING_DIR / "_summary.json"
OUTPUT_MD = FUNDING_DIR / "_summary.md"


def load_funding_programs() -> list[dict]:
    """Load all funding program JSON files from data/funding/."""
    programs = []
    for json_file in sorted(FUNDING_DIR.glob("*.json")):
        if json_file.name.startswith("_"):
            continue  # Skip generated summary files
        try:
            with open(json_file, "r", encoding="utf-8") as f:
                data = json.load(f)
                if isinstance(data, dict) and "id" in data:
                    programs.append(data)
                    print(f"  [OK] Loaded {json_file.name}")
                elif isinstance(data, dict) and "programs" in data:
                    # Handle files with a programs array (e.g., demographic_programs.json)
                    for p in data["programs"]:
                        programs.append(p)
                    print(f"  [OK] Loaded {len(data['programs'])} programs from {json_file.name}")
        except (json.JSONDecodeError, OSError) as e:
            print(f"  [ERROR] Failed to load {json_file.name}: {e}")
    return programs


def generate_summary(programs: list[dict]) -> dict:
    """Generate a summary dict from all programs."""
    return {
        "total_programs": len(programs),
        "programs": [
            {
                "id": p.get("id", "unknown"),
                "name_en": p.get("name_en", ""),
                "type": p.get("type", ""),
                "website": p.get("website", ""),
                "target_group": p.get("target_group", "All entrepreneurs"),
                "description_en": (p.get("description_en", ""))[:200],
            }
            for p in programs
        ],
    }


def generate_markdown(programs: list[dict]) -> str:
    """Generate a Markdown summary of all funding programs."""
    lines = [
        "# BZNS Funding Programs Summary",
        "",
        f"Total programs: **{len(programs)}**",
        "",
        "| ID | Name | Type | Website |",
        "|---|---|---|---|",
    ]
    for p in programs:
        name = p.get("name_en", "")[:50]
        prog_type = p.get("type", "—")
        website = p.get("website", "—")
        pid = p.get("id", "—")
        lines.append(f"| {pid} | {name} | {prog_type} | {website} |")

    lines.append("")
    lines.append("*Generated by generate_funding_summary.py*")
    return "\n".join(lines)


def main():
    print("BZNS Funding Summary Generator")
    print("=" * 40)

    if not FUNDING_DIR.exists():
        print(f"[ERROR] Funding directory not found: {FUNDING_DIR}")
        return

    programs = load_funding_programs()
    print(f"\nLoaded {len(programs)} programs total.")

    # Write JSON summary
    summary = generate_summary(programs)
    with open(OUTPUT_JSON, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2, ensure_ascii=False)
        f.write("\n")
    print(f"[OK] Written JSON summary to {OUTPUT_JSON}")

    # Write Markdown summary
    md = generate_markdown(programs)
    with open(OUTPUT_MD, "w", encoding="utf-8") as f:
        f.write(md)
    print(f"[OK] Written Markdown summary to {OUTPUT_MD}")

    print("\nDone.")


if __name__ == "__main__":
    main()
